"""create projects table

Revision ID: 21a1e02897c7
Revises: 6d7b8f1a2c34
Create Date: 2026-03-09 18:44:34.404307

No-op revision: keeps a linear Alembic chain when an autogenerate run produced an empty
upgrade after `6d7b8f1a2c34` already created `projects`. Safe to leave as-is.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21a1e02897c7'
down_revision: Union[str, Sequence[str], None] = '6d7b8f1a2c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
